version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
